# Set non-blocking status checks
coverage:
  status:
    project:
      default:
        # Allows 10% drop from previous base commit
        threshold: 10%
        informational: true
    patch:
      default:
        informational: true
