name: Add help-wanted issues to help wanted board

on:
  issues:
    types:
      - labeled

permissions: {}

jobs:
  add-help-wanted:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Add issue to project
        id: add-to-project
        uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: https://github.com/orgs/pyOpenSci/projects/3
          # This is a organization level token so it can be used across all repos in our org
          github-token: ${{ secrets.GHPROJECT_HELP_WANTED }}
          labeled: help wanted, sprintable
          label-operator: OR
