name: Add help-wanted issues to help wanted board

on:
  issues:
    types:
      - labeled

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  add-help-wanted:
    name: Add issue to help-wanted project board
    runs-on: ubuntu-latest
    permissions:
      contents: read           # minimum baseline
      issues: write            # required to read issue labels for the action
    steps:
      - name: Add issue to project
        id: add-to-project
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/pyOpenSci/projects/3
          # This is a organization level token so it can be used across all repos in our org
          github-token: ${{ secrets.GHPROJECT_HELP_WANTED }}
          labeled: help wanted, sprintable
          label-operator: OR
