name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # setup build separate from publish
  # See https://github.com/pypa/gh-action-pypi-publish/issues/217#issuecomment-1965727093
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    # This ensures that the publish action only runs in the main repository
    # rather than forks
    environment: build
    permissions:
      contents: read           # read repo for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # This fetch element is only important if you are use SCM based
          # versioning (that looks at git tags to gather the version)
          fetch-depth: 100
          persist-credentials: false

      # Need the tags so that setuptools-scm can form a valid version number
      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"

      - name: Install Hatch
        run: |
          pipx install hatch
          pip list

      - name: Build package using Hatch
        run: |
          hatch build
          echo ""
          echo "Generated files:"
          ls -lh dist/

      # Store an artifact of the build to use in the publish step below
      - name: Store the distribution packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish to PyPI
    if: github.repository_owner == 'pyopensci' && github.event_name == 'release'
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyosmeta
    permissions:
      id-token: write  # mandatory for trusted PyPI publishing
      contents: read
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package to PyPI
        # Only publish to PyPI on release
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
