name: Run pyos meta tests

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Runs on Mon and Thu of each week at 00:00 UTC (see https://crontab.guru)
    - cron: "0 0 * * 1,4"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Test pyosMeta
    runs-on: ubuntu-latest
    permissions:
      contents: read           # read repo for checkout
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.13"

      - name: Install Hatch
        run: pipx install hatch

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hatch run test:run-report

      - name: Run CLIs against website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          pip install -e .
          git clone https://github.com/pyOpenSci/pyopensci.github.io.git
          cd pyopensci.github.io
          update-contributors
          update-reviews
          update-review-teams

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          files: ./coverage.xml
