name: zizmor

on:
  pull_request:
    paths:
      - .github/workflows/**
      - .github/actions/**
      - action.yml
      - action.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - .github/actions/**
      - action.yml
      - action.yaml

permissions: {}

concurrency:
  group: zizmor-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  zizmor:
    name: Static analysis of Actions workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read           # check out the repo
      security-events: write   # upload SARIF to code scanning
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
